org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=384m -XX:ReservedCodeCacheSize=48m -XX:+UseSerialGC -XX:TieredStopAtLevel=1 -Xss512k -Dkotlin.compiler.execution.strategy=in-process
org.gradle.java.home=E:\\jdk17\\jdk-17.0.19+10
kotlin.daemon.jvmargs=-Xmx256m -XX:MaxMetaspaceSize=192m
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.configureondemand=false
org.gradle.workers.max=1
android.useAndroidX=true
android.nonFinalResIds=false
android.nonTransitiveRClass=true
kotlin.incremental=false
